version: '3'
services:
  node:
    build: .
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - '9000:9000'
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: database
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
    restart: always

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass 
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
